name: release

on:
  push:
    branches: [main]
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build Pax
        run: |
          GOOS=darwin GOARCH=amd64 go build -o pax-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o pax-darwin-arm64 .
          GOOS=linux GOARCH=amd64 go build -o pax-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o pax-linux-arm64 .
      - name: Package Pax
        run: |
          mkdir darwin-amd64 darwin-arm64 linux-amd64 linux-arm64
          cp package.toml darwin-amd64
          mv pax-darwin-amd64 darwin-amd64/pax
          cp package.toml darwin-arm64
          mv pax-darwin-arm64 darwin-arm64/pax
          cp package.toml linux-amd64
          mv pax-linux-amd64 linux-amd64/pax
          cp package.toml linux-arm64
          mv pax-linux-arm64 linux-arm64/pax
          (cd darwin-amd64 && tar --zstd cf ../darwin-amd64.apkg *)
          (cd darwin-arm64 && tar --zstd cf ../darwin-arm64.apkg *)
          (cd linux-amd64 && tar --zstd cf ../linux-amd64.apkg *)
          (cd linux-arm64 && tar --zstd cf ../linux-arm64.apkg *)
      - name: Release pax
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            darwin-amd64.apkg
            darwin-arm64.apkg
            linux-amd64.apkg
            linux-arm64.apkg
